version: 0.2

env:
    variables:
        PROJECT: dotnet-backend-api
        DOTNET_CORE_RUNTIME: 5.0

    secrets-manager:
        LOGIN: dotnet-backend-secrets:sonartoken
        HOST: dotnet-backend-secrets:HOST
        Organization: dotnet-backend-secrets:Organization
        Projectkey: dotnet-backend-secrets:Project

phases:   
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}

    commands:
      - echo Installing Entity Framework Core tools reference - .NET CLI
      - dotnet tool install --global dotnet-ef
      - dotnet tool install --global dotnet-sonarscanner
      - apt-get update
      - apt-get install -y jq
        
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - cd ./dotnet-backend-api
      - echo ASPNETCORE_ENVIRONMENT is $ASPNETCORE_ENVIRONMENT
      - echo $ConnectionStrings__DBContext
      - echo Info about dbcontext
      - dotnet ef dbcontext info
      - pwd
      - ls
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet sonarscanner begin /d:sonar.login=$LOGIN /d:sonar.host.url=$HOST /k:$Projectkey /o:$Organization /n:dotnet-backend-api
      - dotnet ef database update
      - dotnet build
      - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Projectkey >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
      - dotnet sonarscanner end /d:sonar.login=$LOGIN

  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release --runtime linux-x64 /property:PublishWithAspNetCoreTargetManifest=false ./${PROJECT}.csproj --self-contained false
      - ls
      - cd bin/
      - ls
      - cd Release/
      - ls
      - cd net5.0/
      - ls
      - cd linux-x64/
      - ls
      - cd publish/
      - ls
      - cd ..
      - cd ..
      - cd ..
      - cd ..
      - cd ..
      #- cd app/
      #- ls
      #- cd publish/
      #- ls
      #- cd ..
      #- cd ..
      - pwd
      - ls
      
artifacts:
  files:
    - ./dotnet-backend-api/bin/Release/net5.0/linux-x64/publish/**/*
    - ./dotnet-backend-api/Dockerfile
    - ./dotnet-backend-api/taskdef.json
    - ./dotnet-backend-api/appspec.yaml
    - ./db-migrations-spec.yml
  discard-paths: yes