version: 0.2



env:
    variables:
        PROJECT: dotnet-backend-api
        DOTNET_CORE_RUNTIME: 5.0
phases:   
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
        
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - cd ./dotnet-backend-api
      - pwd
      - ls
    #  - dotnet restore dotnet-backend-api.csproj
      
  build:
    commands:
      - echo Build started on `date`
    #  - dotnet build -c Release
      
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release --runtime linux-x64 /property:PublishWithAspNetCoreTargetManifest=false ./${PROJECT}.csproj --self-contained false 
      - ls
      - cd bin/
      - ls
      - cd Release/
      - ls
      - cd net5.0/
      - ls
      - cd linux-x64/
      - ls
      - cd publish/
      - ls
      - cd ..
      - cd ..
      - cd ..
      - cd ..
      - cd ..
      #- cd app/
      #- ls
      #- cd publish/
      #- ls
      #- cd ..
      #- cd ..
      - pwd
      - ls
      
artifacts:
  files:
    - ./dotnet-backend-api/bin/Release/net5.0/linux-x64/publish/**/*
    - ./dotnet-backend-api/Dockerfile
    - ./dotnet-backend-api/taskdef.json
    - ./dotnet-backend-api/appspec.yaml
    - ./db-migrations-spec.yml
  discard-paths: yes