version: 0.2



env:
    variables:
        PROJECT: dotnet-backend-api
        DOTNET_CORE_RUNTIME: 5.0
phases:   
  install:
    runtime-versions:
      dotnet: ${DOTNET_CORE_RUNTIME}
        
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - cd ./dotnet-backend-api
      - pwd
      - ls
      - dotnet restore dotnet-backend-api.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build -c Release -o ./app/build
      
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 -o ./app/publish ./${PROJECT}.csproj --self-contained false
      - cd build_output
      - ls
     # - cp Procfile ./build_ouput
      
artifacts:
  files:
    - ./app/publish/*
    - Dockerfile
  discard-paths: no